
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or first_project intended use of these models
name: 'first_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "dbt-snowflake"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  # Be sure to namespace your model configs to your project name

  first_project:
    # Config indicated by + and applies to all files under models/example/
    +database: "db_analytics"

    staging:
      +materialized: view
      +schema: staging

      # This configures models found in models/staging/master_table
      master_table:
        +materialized: ephemeral

    marts:
      +materialized: table

      # This configures models found in models/marts/intermediate
      intermediate:
        +schema: intermediate

      # This configures models found in models/marts/core
      core:
        +schema: core