first_project:
  target: my_target
  outputs:
    user_space:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT_ID') }}"
      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      # Want to update threads count? see this: https://discourse.getdbt.com/t/cannot-import-name-snowflakeocspasn1crypto-from-partially-initialized-module-occurs-when-running-dbt-test/2905/2
      threads: "{{ env_var('DBT_THREADS', '1') | int }}"
      client_session_keep_alive: False
      query_tag: "coba"
      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false